package com.fluxpay.common.enums;

public enum WebhookEventType {
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_UPDATED,
    SUBSCRIPTION_CANCELED,
    SUBSCRIPTION_PAUSED,
    SUBSCRIPTION_RESUMED,
    INVOICE_CREATED,
    INVOICE_FINALIZED,
    INVOICE_PAID,
    INVOICE_PAYMENT_FAILED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    CUSTOMER_CREATED,
    CUSTOMER_UPDATED
}

